upstream mes_applications {
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
}

# Serveur HTTPS
server {
    listen 8443 ssl; # Écoute sur le port 8443 en SSL
    server_name mon-super-site.local;

    # Chemins vers les certificats générés à l'étape 1
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    # Protocoles de sécurité recommandés
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://mes_applications;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Indique à tes serveurs d'application que la requête d'origine était sécurisée
        proxy_set_header X-Forwarded-Proto $scheme; 
    }
}

# Redirection automatique du HTTP vers le HTTPS
server {
    listen 8080;
    server_name mon-super-site.local;
    return 301 https://$host:8443$request_uri;
}