# 1. Le bloc upstream est TOUT SEUL (en dehors du bloc server)
upstream mes_applications {
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
}

# 2. Le bloc server commence après
server {
    listen 8080;
    server_name mon-super-site.local;

    location / {
        proxy_pass http://mes_applications;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}