apiVersion: v1
kind: Service
metadata:
  name: gpi-service
spec:
  selector:
    app:  gpi-pivot
# ...
  ports:
    - port: 80
      targetPort: 9000 # <-- CHANGER 9000 PAR 8000
      nodePort: 30090
  type: NodePort